In [1]:
%pip install pandas sqlalchemy psycopg2-binary requests

Requirement already satisfied: pandas in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (2.3.0)
Requirement already satisfied: sqlalchemy in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (2.0.49)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp311-cp311-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: requests in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (2.32.4)
Requirement already satisfied: numpy>=1.23.2 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from pandas) (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from sqlalchemy) (4.14.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from requests) (2025.6.15)
Requirement already satisfied: six>=1.5 in c:\users\arthu\anaconda3\envs\pyspark\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading psycopg2_binary-2.9.12-cp311-cp311-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   -------------------------------------- - 2.6/2.8 MB 18.9 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 16.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests
import pandas as pd
from sqlalchemy import create_engine, inspect
import time

# 1. Rallumer le cluster via l'API du simulateur
api_url = "http://localhost:8000/cluster/power"
try:
    res = requests.post(api_url, json={"action": "on"})
    print("Commande d'allumage :", res.json())
except Exception as e:
    print("Erreur de connexion à l'API :", e)

# On laisse le système tourner un peu pour accumuler de la télémétrie fraîche
print("Attente de 15 secondes pour générer de la donnée continue...")
time.sleep(15)

# 2. Connexion à la base TimescaleDB
db_url = "postgresql://jumeaux:jumeaux@localhost:5432/jumeaux"
engine = create_engine(db_url)

# 3. Inspection dynamique pour trouver la table de télémétrie
inspector = inspect(engine)
tables = inspector.get_table_names()
print("\nTables détectées dans TimescaleDB :", tables)

# On sélectionne logiquement la première table (qui devrait s'appeler 'telemetry', 'metrics' ou équivalent)
table_name = tables[0] if tables else None

Commande d'allumage : {'ok': True, 'message': 'srv-master-01=ok, srv-master-02=ok, srv-worker-01=ok, srv-worker-02=ok, srv-worker-03=ok'}
Attente de 15 secondes pour générer de la donnée continue...

Tables détectées dans TimescaleDB : ['telemetry', 'events']

In [20]:
import pandas as pd
from sqlalchemy import create_engine, inspect

# 1. Connexion à TimescaleDB
db_url = "postgresql://jumeaux:jumeaux@localhost:5432/jumeaux"
engine = create_engine(db_url)

# 2. Vérification de la table et extraction
table_name = 'telemetry'

query = f"""
SELECT ts, cluster_id, machine_id, status, temperature_c, fan_rpm_avg 
FROM {table_name}
ORDER BY ts ASC
LIMIT 10000;
"""

df = pd.read_sql(query, engine)

# Conversion en datetime et indexation
df['ts'] = pd.to_datetime(df['ts'])
df.set_index('ts', inplace=True)

# Tri crucial : par machine puis par temps
df.sort_values(['machine_id', 'ts'], inplace=True)

# -- FEATURE ENGINEERING DYNAMIQUE --

# 1. Moyenne glissante (lissage du bruit sur 30s)
df['temp_rolling_mean_30s'] = df.groupby('machine_id')['temperature_c'].transform(
    lambda x: x.rolling('30s').mean()
)

# 2. Dérivée temporelle (vitesse de chauffe entre la mesure actuelle et la précédente)
df['temp_diff'] = df.groupby('machine_id')['temperature_c'].transform(
    lambda x: x.diff()
)

# 3. Variance / Écart-type (détection d'instabilité sur 60s)
df['temp_std_60s'] = df.groupby('machine_id')['temperature_c'].transform(
    lambda x: x.rolling('60s').std()
)

# Suppression des valeurs nulles dues à l'initialisation des fenêtres glissantes
df.dropna(inplace=True)

# Affichage du résultat
display(df.head(10))

Empty DataFrame
Columns: [cluster_id, machine_id, status, temperature_c, fan_rpm_avg, temp_rolling_mean_30s, temp_diff, temp_std_60s]
Index: []

In [24]:
import requests
import pandas as pd
import time
from sqlalchemy import create_engine

print("1. Allumage du cluster...")
requests.post("http://localhost:8000/cluster/power", json={"action": "on"})

print("2. Attente de la télémétrie (10 secondes)...")
time.sleep(10)

print("3. Interrogation de TimescaleDB...")
db_url = "postgresql://jumeaux:jumeaux@localhost:5432/jumeaux"
engine = create_engine(db_url)

query = """
SELECT ts, machine_id, status, temperature_c, fan_rpm_avg 
FROM telemetry
ORDER BY ts ASC;
"""
df = pd.read_sql(query, engine)

print(f"Nombre de lignes collectées : {len(df)}")
if len(df) > 0:
    display(df.tail())

1. Allumage du cluster...
2. Attente de la télémétrie (10 secondes)...
3. Interrogation de TimescaleDB...
Nombre de lignes collectées : 0

In [26]:
import requests
import pandas as pd
import time
from sqlalchemy import create_engine

print("1. Allumage du cluster...")
try:
    res = requests.post("http://localhost:8000/cluster/power", json={"action": "on"})
    print(res.json())
except Exception as e:
    print("Erreur API :", e)

print("2. Attente de la télémétrie (10 secondes)...")
time.sleep(10)

print("3. Interrogation de TimescaleDB...")
db_url = "postgresql://jumeaux:jumeaux@localhost:5432/jumeaux"
engine = create_engine(db_url)

query = """
SELECT ts, machine_id, status, temperature_c, fan_rpm_avg 
FROM telemetry
ORDER BY ts ASC;
"""
df = pd.read_sql(query, engine)

print(f"Nombre de lignes collectées : {len(df)}")
if len(df) > 0:
    display(df.tail())

1. Allumage du cluster...
{'ok': True, 'message': 'srv-master-01=ok, srv-master-02=ok, srv-worker-01=ok, srv-worker-02=ok, srv-worker-03=ok'}
2. Attente de la télémétrie (10 secondes)...
3. Interrogation de TimescaleDB...
Nombre de lignes collectées : 0

In [27]:
import requests
import pandas as pd
import time
from IPython.display import display

print("1. Forçage de l'allumage des serveurs...")
try:
    requests.post("http://localhost:8000/cluster/power", json={"action": "on"})
except Exception as e:
    print("Erreur de connexion API:", e)

print("2. Scraping du Jumeau Numérique en cours (Patientez 45 secondes)...")
data_list = []

# Collecte d'un snapshot par seconde pendant 45 secondes
for i in range(45):
    try:
        res = requests.get("http://localhost:8000/cluster/status")
        if res.status_code == 200:
            cluster_data = res.json()
            ts = cluster_data['ts']
            
            # Parcours de chaque machine du cluster
            for mac_id, mac_info in cluster_data.get('machines', {}).items():
                # Calcul rapide de la moyenne des RPM pour les ventilateurs
                fans = mac_info.get('fans', [])
                avg_rpm = sum(f.get('rpm', 0) for f in fans) / len(fans) if fans else 0
                
                data_list.append({
                    'ts': pd.to_datetime(ts),
                    'machine_id': mac_id,
                    'status': mac_info.get('status'),
                    'temperature_c': mac_info.get('temperature_c'),
                    'fan_rpm_avg': avg_rpm
                })
    except Exception:
        pass
    
    # Pause d'une seconde pour respecter le rythme d'ingestion
    time.sleep(1)

# Transformation en DataFrame structuré
df = pd.DataFrame(data_list)

if len(df) > 0:
    print(f"\n✅ Succès absolu : {len(df)} observations collectées à la source !")
    
    # Indexation temporelle stricte pour les calculs de fenêtres glissantes
    df.sort_values(['machine_id', 'ts'], inplace=True)
    df.set_index('ts', inplace=True)
    
    # 1. Feature : Moyenne lissée sur 15s (absorbe le bruit du capteur)
    df['temp_mean_15s'] = df.groupby('machine_id')['temperature_c'].transform(
        lambda x: x.rolling('15s').mean()
    )
    
    # 2. Feature : Accélération thermique (Dérivée)
    df['temp_diff'] = df.groupby('machine_id')['temperature_c'].transform(
        lambda x: x.diff()
    )
    
    df.dropna(inplace=True)
    display(df.tail(15))
else:
    print("❌ L'API n'a retourné aucune donnée. Le simulateur est figé.")

1. Forçage de l'allumage des serveurs...
2. Scraping du Jumeau Numérique en cours (Patientez 45 secondes)...

✅ Succès absolu : 225 observations collectées à la source !

,machine_id,status,temperature_c,fan_rpm_avg,temp_mean_15s,temp_diff
ts,,,,,,
2026-05-20 08:23:46.450549+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:47.461535+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:48.473244+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:49.481591+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:50.491503+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:51.500370+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:52.509611+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:53.518249+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:54.527913+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:55.536430+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:56.545742+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:57.553880+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:58.563908+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:23:59.573532+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0
2026-05-20 08:24:00.582352+00:00,srv-worker-03,on,22.058217,2.0,22.058217,0.0

In [31]:
# 1. Création d'une variable binaire immédiate (0 = OK, 1 = Panne)
df['is_failed'] = df['status'].apply(lambda x: 1 if x in ['off', 'degraded'] else 0)

# 2. Préparation à l'inversion : on sort temporairement 'ts' de l'index
df.reset_index(inplace=True)

# 3. Tri inversé : on classe par machine, et par temps DÉCROISSANT (du futur vers le passé)
df.sort_values(['machine_id', 'ts'], ascending=[True, False], inplace=True)

# 4. Calcul de la fenêtre d'anticipation
# Comme notre intervalle est d'une ligne par seconde, on regarde les 45 lignes suivantes
df['failure_in_45s'] = df.groupby('machine_id')['is_failed'].transform(
    lambda x: x.rolling(window=45, min_periods=1).max()
)

# 5. Restauration de la chronologie : on remet dans l'ordre croissant et on ré-indexe
df.sort_values(['machine_id', 'ts'], ascending=[True, True], inplace=True)
df.set_index('ts', inplace=True)

# 6. Nettoyage de la variable intermédiaire
df.drop(columns=['is_failed'], inplace=True)

# Résultat
alertes = df['failure_in_45s'].sum()
print(f"Nombre d'observations nécessitant une intervention préventive : {alertes}")

# Affichage des instants critiques où l'algorithme indique qu'une panne va arriver
if alertes > 0:
    display(df[df['failure_in_45s'] == 1].head(10))
else:
    print("Aucune panne n'est survenue dans cet échantillon de 45 secondes.")

Nombre d'observations nécessitant une intervention préventive : 0.0
Aucune panne n'est survenue dans cet échantillon de 45 secondes.

In [34]:
import requests
import pandas as pd
import time
from IPython.display import display

print("1. Initialisation : Rallumage du cluster...")
try:
    requests.post("http://localhost:8000/cluster/power", json={"action": "on"})
except Exception:
    pass

print("2. Début de l'enregistrement (Durée prévue : 150 secondes)...")
data_list = []

for i in range(150):
    # --- SCRAPING DU SNAPSHOT ---
    try:
        res = requests.get("http://localhost:8000/cluster/status")
        if res.status_code == 200:
            cluster_data = res.json()
            ts = cluster_data['ts']
            
            for mac_id, mac_info in cluster_data.get('machines', {}).items():
                fans = mac_info.get('fans', [])
                avg_rpm = sum(f.get('rpm', 0) for f in fans) / len(fans) if fans else 0
                
                data_list.append({
                    'ts': pd.to_datetime(ts),
                    'machine_id': mac_id,
                    'status': mac_info.get('status'),
                    'temperature_c': mac_info.get('temperature_c'),
                    'fan_rpm_avg': avg_rpm
                })
    except Exception:
        pass
    
    # --- SABOTAGE CONTRÔLÉ À T+15 SECONDES ---
    if i == 15:
        print("\n>> ⚡ Sabotage en cours : Injection d'une surcharge (power_surge) sur srv-master-01...")
        try:
            # CORRECTION DU SCHEMA JSON : "fault_type" au lieu de "type"
            res_fault = requests.post(
                "http://localhost:8000/simulation/fault", 
                json={"machine_id": "srv-master-01", "fault_type": "power_surge"}
            )
            if res_fault.status_code == 200:
                print("   -> ✅ Injection acceptée par l'API ! La température va monter.\n")
            else:
                print(f"   -> ❌ Échec de l'injection : {res_fault.status_code} - {res_fault.text}\n")
        except Exception as e:
            print("Échec de l'injection (Erreur réseau) :", e)
            
    # On affiche un petit point de progression toutes les 30 secondes
    if i > 0 and i % 30 == 0:
        print(f"... {i} secondes écoulées")
        
    time.sleep(1)

# --- TRAITEMENT ET FEATURE ENGINEERING ---
df = pd.DataFrame(data_list)

if len(df) > 0:
    print(f"\n✅ {len(df)} observations collectées. Calcul des variables...")
    
    # Tri et indexation
    df.sort_values(['machine_id', 'ts'], inplace=True)
    df.set_index('ts', inplace=True)
    
    # Variables dynamiques
    df['temp_mean_15s'] = df.groupby('machine_id')['temperature_c'].transform(lambda x: x.rolling('15s').mean())
    df['temp_diff'] = df.groupby('machine_id')['temperature_c'].transform(lambda x: x.diff())
    
    # --- CRÉATION DU LABEL D'ANTICIPATION (Y) ---
    df.reset_index(inplace=True)
    df['is_failed'] = df['status'].apply(lambda x: 1 if x in ['off', 'degraded'] else 0)
    
    # Inversion temporelle pour lire l'avenir
    df.sort_values(['machine_id', 'ts'], ascending=[True, False], inplace=True)
    
    # Y = 1 si la machine s'éteint dans les 45 prochaines secondes
    df['failure_in_45s'] = df.groupby('machine_id')['is_failed'].transform(
        lambda x: x.rolling(window=45, min_periods=1).max()
    )
    
    # Restauration de l'ordre normal
    df.sort_values(['machine_id', 'ts'], ascending=[True, True], inplace=True)
    df.set_index('ts', inplace=True)
    df.drop(columns=['is_failed'], inplace=True)
    df.dropna(inplace=True)
    
    # --- ANALYSE DES RÉSULTATS ---
    alertes = df['failure_in_45s'].sum()
    print(f"\n🚨 Nombre de lignes nécessitant une alerte préventive : {alertes}")
    
    if alertes > 0:
        print("\nVoici un extrait des moments critiques (la montée en température avant l'arrêt) :")
        display(df[(df['machine_id'] == 'srv-master-01') & (df['failure_in_45s'] == 1)].head(15))
else:
    print("❌ Aucune donnée récoltée.")

1. Initialisation : Rallumage du cluster...
2. Début de l'enregistrement (Durée prévue : 150 secondes)...

>> ⚡ Sabotage en cours : Injection d'une surcharge (power_surge) sur srv-master-01...
   -> ✅ Injection acceptée par l'API ! La température va monter.

... 30 secondes écoulées
... 60 secondes écoulées
... 90 secondes écoulées
... 120 secondes écoulées

✅ 750 observations collectées. Calcul des variables...

🚨 Nombre de lignes nécessitant une alerte préventive : 0.0

In [36]:
import requests
import pandas as pd
import time
from IPython.display import display

print("1. Rallumage du cluster...")
try:
    requests.post("http://localhost:8000/cluster/power", json={"action": "on"})
except Exception:
    pass

# On laisse la température se stabiliser quelques secondes
time.sleep(5)

print("\n2. 🛑 SABOTAGE ABSOLU : Blocage du système de refroidissement sur srv-master-01")
try:
    success = True
    # Le serveur master possède 2 ventilateurs (index 0 et 1)
    for idx in [0, 1]:
        # On force chaque ventilateur en mode manuel avec son fan_idx
        res_mode = requests.put(
            "http://localhost:8000/machines/srv-master-01/fan_mode", 
            json={"fan_idx": idx, "mode": "manual"}
        )
        # On met leur vitesse de rotation à 0 RPM (et non en pourcentage)
        res_speed = requests.put(
            "http://localhost:8000/machines/srv-master-01/fan_speed", 
            json={"fan_idx": idx, "rpm": 0}
        )
        
        if res_mode.status_code != 200 or res_speed.status_code != 200:
            success = False
            print(f"   -> ⚠️ Erreur sur le ventilateur {idx} :", res_mode.text, res_speed.text)

    if success:
        print("   -> ✅ Ventilateurs 0 et 1 bloqués à 0 RPM ! La machine ne peut plus se refroidir.")

    # On ajoute la surcharge électrique pour accélérer la chauffe
    requests.post(
        "http://localhost:8000/simulation/fault", 
        json={"machine_id": "srv-master-01", "fault_type": "power_surge"}
    )
    print("   -> ✅ Surcharge électrique injectée.")
except Exception as e:
    print("Erreur de connexion :", e)


print("\n3. Début de l'enregistrement de l'emballement thermique (Durée : 100 secondes)...")
data_list = []

for i in range(100):
    # --- SCRAPING DU SNAPSHOT ---
    try:
        res = requests.get("http://localhost:8000/cluster/status")
        if res.status_code == 200:
            cluster_data = res.json()
            ts = cluster_data['ts']
            
            for mac_id, mac_info in cluster_data.get('machines', {}).items():
                fans = mac_info.get('fans', [])
                avg_rpm = sum(f.get('rpm', 0) for f in fans) / len(fans) if fans else 0
                
                data_list.append({
                    'ts': pd.to_datetime(ts),
                    'machine_id': mac_id,
                    'status': mac_info.get('status'),
                    'temperature_c': mac_info.get('temperature_c'),
                    'fan_rpm_avg': avg_rpm
                })
    except Exception:
        pass
        
    time.sleep(1)

# --- TRAITEMENT ET FEATURE ENGINEERING ---
df = pd.DataFrame(data_list)

if len(df) > 0:
    print(f"\n✅ Observations collectées. Création du Dataset Machine Learning...")
    
    df.sort_values(['machine_id', 'ts'], inplace=True)
    df.set_index('ts', inplace=True)
    
    # 1. Variables dynamiques
    df['temp_mean_15s'] = df.groupby('machine_id')['temperature_c'].transform(lambda x: x.rolling('15s').mean())
    df['temp_diff'] = df.groupby('machine_id')['temperature_c'].transform(lambda x: x.diff())
    
    # 2. Variable cible (Y) d'anticipation
    df.reset_index(inplace=True)
    df['is_failed'] = df['status'].apply(lambda x: 1 if x in ['off', 'degraded'] else 0)
    
    df.sort_values(['machine_id', 'ts'], ascending=[True, False], inplace=True)
    
    df['failure_in_45s'] = df.groupby('machine_id')['is_failed'].transform(
        lambda x: x.rolling(window=45, min_periods=1).max()
    )
    
    df.sort_values(['machine_id', 'ts'], ascending=[True, True], inplace=True)
    df.set_index('ts', inplace=True)
    df.drop(columns=['is_failed'], inplace=True)
    df.dropna(inplace=True)
    
    alertes = df['failure_in_45s'].sum()
    print(f"\n🚨 Lignes étiquetées en alerte préventive : {alertes}")
    
    if alertes > 0:
        print("\nVoici les instants fatidiques que ton modèle devra apprendre à reconnaître :")
        # On affiche uniquement les moments critiques du serveur ciblé
        display(df[(df['machine_id'] == 'srv-master-01') & (df['failure_in_45s'] == 1)].head(15))
else:
    print("❌ Aucune donnée récoltée.")

1. Rallumage du cluster...

2. 🛑 SABOTAGE ABSOLU : Blocage du système de refroidissement sur srv-master-01
   -> ✅ Ventilateurs 0 et 1 bloqués à 0 RPM ! La machine ne peut plus se refroidir.
   -> ✅ Surcharge électrique injectée.

3. Début de l'enregistrement de l'emballement thermique (Durée : 100 secondes)...

✅ Observations collectées. Création du Dataset Machine Learning...

🚨 Lignes étiquetées en alerte préventive : 0.0

In [3]:
import requests
import pandas as pd
import time
from IPython.display import display

print("1. Rallumage du cluster...")
try:
    requests.post("http://localhost:8000/cluster/power", json={"action": "on"})
except: pass

time.sleep(5)

print("\n2. 🛑 SABOTAGE ABSOLU : Refroidissement HS + Surtension Prolongée")
try:
    # 1. Coupure des ventilateurs
    for idx in [0, 1]:
        requests.put(f"http://localhost:8000/machines/srv-master-01/fan_mode", json={"fan_idx": idx, "mode": "manual"})
        requests.put(f"http://localhost:8000/machines/srv-master-01/fan_speed", json={"fan_idx": idx, "rpm": 0})
    
    # 2. Injection d'une panne VIOLENTE et LONGUE (120 secondes, magnitude x2)
    requests.post(
        "http://localhost:8000/simulation/fault", 
        json={
            "machine_id": "srv-master-01", 
            "fault_type": "power_surge",
            "duration_s": 120.0,
            "magnitude": 2.0
        }
    )
    print("   -> ✅ Sabotage total injecté (Ventilos = 0, Surtension = x2 sur 120s).")
except Exception as e:
    print("Erreur :", e)

print("\n3. Enregistrement de l'emballement thermique (Durée : 100 secondes)...")
data_list = []

for i in range(100):
    try:
        res = requests.get("http://localhost:8000/cluster/status")
        if res.status_code == 200:
            cluster_data = res.json()
            ts = cluster_data['ts']
            for mac_id, mac_info in cluster_data.get('machines', {}).items():
                data_list.append({
                    'ts': pd.to_datetime(ts),
                    'machine_id': mac_id,
                    'status': mac_info.get('status'),
                    'temperature_c': mac_info.get('temperature_c')
                })
    except: pass
    time.sleep(1)

# --- TRAITEMENT ---
df = pd.DataFrame(data_list)
df.sort_values(['machine_id', 'ts'], inplace=True)
df.set_index('ts', inplace=True)

df['temp_mean_15s'] = df.groupby('machine_id')['temperature_c'].transform(lambda x: x.rolling('15s').mean())
df['temp_diff'] = df.groupby('machine_id')['temperature_c'].transform(lambda x: x.diff())

df.reset_index(inplace=True)
df['is_failed'] = df['status'].apply(lambda x: 1 if x in ['off', 'degraded'] else 0)

df.sort_values(['machine_id', 'ts'], ascending=[True, False], inplace=True)
df['failure_in_45s'] = df.groupby('machine_id')['is_failed'].transform(lambda x: x.rolling(window=45, min_periods=1).max())
df.sort_values(['machine_id', 'ts'], ascending=[True, True], inplace=True)

df.set_index('ts', inplace=True)
df.drop(columns=['is_failed'], inplace=True)
df.dropna(inplace=True)

# DIAGNOSTIC
master_df = df[df['machine_id'] == 'srv-master-01']
print(f"\n📈 Température maximale atteinte par srv-master-01 : {master_df['temperature_c'].max():.1f} °C")

alertes = df['failure_in_45s'].sum()
print(f"🚨 Lignes étiquetées en alerte préventive : {alertes}")

if alertes > 0:
    display(master_df[master_df['failure_in_45s'] == 1].head(10))

1. Rallumage du cluster...

2. 🛑 SABOTAGE ABSOLU : Refroidissement HS + Surtension Prolongée
   -> ✅ Sabotage total injecté (Ventilos = 0, Surtension = x2 sur 120s).

3. Enregistrement de l'emballement thermique (Durée : 100 secondes)...

📈 Température maximale atteinte par srv-master-01 : 113.7 °C
🚨 Lignes étiquetées en alerte préventive : 99.0

,machine_id,status,temperature_c,temp_mean_15s,temp_diff,failure_in_45s
ts,,,,,,
2026-05-21 09:23:32.143715+00:00,srv-master-01,on,67.531877,63.419833,8.224087,1.0
2026-05-21 09:23:33.156803+00:00,srv-master-01,on,76.573759,67.804475,9.041882,1.0
2026-05-21 09:23:34.166068+00:00,srv-master-01,on,85.582075,72.248875,9.008316,1.0
2026-05-21 09:23:35.175852+00:00,srv-master-01,off,90.240910,75.847282,4.658835,1.0
2026-05-21 09:23:36.185729+00:00,srv-master-01,off,90.687938,78.320725,0.447028,1.0
2026-05-21 09:23:37.194419+00:00,srv-master-01,off,91.130023,80.150625,0.442086,1.0
2026-05-21 09:23:38.201743+00:00,srv-master-01,off,91.567221,81.577699,0.437198,1.0
2026-05-21 09:23:39.210066+00:00,srv-master-01,off,91.999586,82.735687,0.432365,1.0
2026-05-21 09:23:40.219777+00:00,srv-master-01,off,92.427171,83.704835,0.427585,1.0
2026-05-21 09:23:41.228651+00:00,srv-master-01,off,92.850028,84.536216,0.422857,1.0

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

print("1. Préparation des données...")
# Sélection des variables explicatives (Features)
# On exclut la température absolue brute pour forcer le modèle à comprendre la dynamique temporelle
features = ['temp_mean_15s', 'temp_diff', 'fan_rpm_avg']
X = df[features]
y = df['failure_in_45s']

# Séparation chronologique : 70% Entraînement / 30% Test
split_idx = int(len(df) * 0.70)
X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

print(f"   -> Entraînement sur {len(X_train)} lignes, Test sur {len(X_test)} lignes.")

print("\n2. Entraînement du modèle (Random Forest)...")
# On utilise class_weight='balanced' pour dire au modèle de donner beaucoup d'importance aux pannes (les 1)
model = RandomForestClassifier(n_estimators=100, max_depth=5, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

print("\n3. Évaluation sur les données du futur (Test set)...")
y_pred = model.predict(X_test)

print("\n--- MATRICE DE CONFUSION ---")
cm = confusion_matrix(y_test, y_pred)
print(f"Vrais Négatifs (OK bien prédits) : {cm[0][0]}")
print(f"Faux Positifs (Fausses alertes)   : {cm[0][1]}")
print(f"Faux Négatifs (Pannes ratées)    : {cm[1][0]}")
print(f"Vrais Positifs (Pannes anticipées): {cm[1][1]}")

print("\n--- RAPPORT DE CLASSIFICATION ---")
print(classification_report(y_test, y_pred, target_names=["Nominal (0)", "Alerte Panne (1)"]))

# Affichage de l'importance des variables pour comprendre la logique de l'IA
importances = model.feature_importances_
print("\n--- IMPORTANCE DES VARIABLES ---")
for feat, imp in zip(features, importances):
    print(f" - {feat:15s} : {imp*100:.1f} %")

ModuleNotFoundError: No module named 'sklearn'

In [4]:
%pip install sklearn

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.